### ISSUE TITLE
Http connection is leaking - OkHttp response body is not closed

### ISSUE THREAD

**Issue by sivaramvanka** [bazaarvoice/bv-android-sdk#16]
OkHttp response body is not closed in the bv-android-sdk. 
I believe it's Analytics Manager. Please see the logs below.

04-14 06:15:36.152 17709-17709/? E/Zygote: MountEmulatedStorage()
04-14 06:15:36.162 17709-17709/? E/Zygote: v2
04-14 06:15:36.162 17709-17709/? I/libpersona: KNOX_SDCARD checking this for 10252
04-14 06:15:36.162 17709-17709/? I/libpersona: KNOX_SDCARD not a persona
04-14 06:15:36.162 17709-17709/? I/SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SAMSUNG-SM-G920A_5.0.2_0011
04-14 06:15:36.162 17709-17709/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-14 06:15:36.162 17709-17709/? I/art: Late-enabling -Xcheck:jni
04-14 06:15:36.172 17709-17709/com.bazaarvoice.bv_android_sdk D/TimaKeyStoreProvider: TimaSignature is unavailable
04-14 06:15:36.172 17709-17709/com.bazaarvoice.bv_android_sdk D/ActivityThread: Added TimaKeyStore provider
04-14 06:15:36.212 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
04-14 06:15:36.212 17709-17709/com.bazaarvoice.bv_android_sdk W/ActivityThread: Application com.bazaarvoice.bv_android_sdk is waiting for the debugger on port 8100...
04-14 06:15:36.212 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: Sending WAIT chunk
04-14 06:15:36.222 17709-17716/com.bazaarvoice.bv_android_sdk I/art: Debugger is active
04-14 06:15:36.412 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: Debugger has connected
04-14 06:15:36.412 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:36.612 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:36.822 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:37.022 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:37.222 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:37.422 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:37.622 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:37.822 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:38.022 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: waiting for debugger to settle...
04-14 06:15:38.222 17709-17709/com.bazaarvoice.bv_android_sdk I/System.out: debugger has settled (1489)
04-14 06:15:38.222 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: Inside getClassLibPath caller 
04-14 06:15:38.272 17709-17765/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: getUserAdvertisingId - fetched: false, userAdvertisingId: null
04-14 06:15:38.272 17709-17765/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: Search for profile at https://my.network-stg.bazaarvoice.com/users/magpie_idfa_pending?passkey
04-14 06:15:38.282 17709-17709/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: getUserAdvertisingId - fetched: false, userAdvertisingId: null
04-14 06:15:38.292 17709-17709/com.bazaarvoice.bv_android_sdk D/InjectionManager: InjectionManager
04-14 06:15:38.292 17709-17709/com.bazaarvoice.bv_android_sdk D/InjectionManager: fillFeatureStoreMap com.bazaarvoice.bv_android_sdk
04-14 06:15:38.292 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: Constructor com.bazaarvoice.bv_android_sdk, Feature store :{}
04-14 06:15:38.292 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: featureStore :{}
04-14 06:15:38.332 17709-17709/com.bazaarvoice.bv_android_sdk D/PhoneWindow: *FMB* installDecor mIsFloating : false
04-14 06:15:38.332 17709-17709/com.bazaarvoice.bv_android_sdk D/PhoneWindow: *FMB* installDecor flags : -2139029248
04-14 06:15:38.432 17709-17709/com.bazaarvoice.bv_android_sdk D/Activity: performCreate Call Injection manager
04-14 06:15:38.432 17709-17709/com.bazaarvoice.bv_android_sdk V/BVActivityLifecycleCallbacks: application resume
04-14 06:15:38.432 17709-17709/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: getUserAdvertisingId - fetched: false, userAdvertisingId: null
04-14 06:15:38.442 17709-17709/com.bazaarvoice.bv_android_sdk W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
04-14 06:15:38.452 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: dispatchOnViewCreated > Target : com.example.bazaarvoice.bv_android_sdk.MainActivity isFragment :false
04-14 06:15:38.462 17709-17783/com.bazaarvoice.bv_android_sdk D/OpenGLRenderer: Render dirty regions requested: true
04-14 06:15:38.462 17709-17764/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: setIsLimitadTrackingEnabled: false
04-14 06:15:38.472 17709-17709/com.bazaarvoice.bv_android_sdk D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
04-14 06:15:38.472 17709-17709/com.bazaarvoice.bv_android_sdk D/PhoneWindow: *FMB* isFloatingMenuEnabled return false
04-14 06:15:38.532 17709-17783/com.bazaarvoice.bv_android_sdk D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
04-14 06:15:38.552 17709-17783/com.bazaarvoice.bv_android_sdk I/OpenGLRenderer: Initialized EGL, version 1.4
04-14 06:15:38.562 17709-17783/com.bazaarvoice.bv_android_sdk I/OpenGLRenderer: HWUI protection enabled for context ,  &this =0x7f70142060 ,&mEglDisplay = 1 , &mEglConfig = 1880904368 
04-14 06:15:38.562 17709-17783/com.bazaarvoice.bv_android_sdk D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 8192
04-14 06:15:38.562 17709-17783/com.bazaarvoice.bv_android_sdk D/OpenGLRenderer: Enabling debug mode 0
04-14 06:15:38.562 17709-17783/com.bazaarvoice.bv_android_sdk D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
04-14 06:15:38.612 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: dispatchCreateOptionsMenu :com.example.bazaarvoice.bv_android_sdk.MainActivity
04-14 06:15:38.612 17709-17709/com.bazaarvoice.bv_android_sdk I/InjectionManager: dispatchPrepareOptionsMenu :com.example.bazaarvoice.bv_android_sdk.MainActivity
04-14 06:15:38.672 17709-17709/com.bazaarvoice.bv_android_sdk I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@39ce35c2 time:203970300
04-14 06:15:38.772 17709-17765/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: Profile response:
                                                                                                                  Response{protocol=http/1.1, code=403, message=Forbidden, url=https://my.network-stg.bazaarvoice.com/users/magpie_idfa_pending?passkey}
04-14 06:15:38.772 17709-17765/com.bazaarvoice.bv_android_sdk D/Profile: Unsuccesfully updated profile, response code 403
04-14 06:15:58.542 17709-17767/com.bazaarvoice.bv_android_sdk D/Analytics: Successfully posted 2 events
04-14 06:16:38.392 17709-17709/com.bazaarvoice.bv_android_sdk V/BVActivityLifecycleCallbacks: application pause
04-14 06:16:38.392 17709-17709/com.bazaarvoice.bv_android_sdk D/com.bazaarvoice.bvandroidsdk.BVAuthenticatedUser: getUserAdvertisingId - fetched: true, userAdvertisingId: c759dad0-0076-4304-a8ef-7ac01e9fa34f
04-14 06:16:46.362 17709-17777/com.bazaarvoice.bv_android_sdk W/okhttp3.OkHttpClient: A connection to https://my.network-stg.bazaarvoice.com/ was leaked. Did you forget to close a response body?
04-14 06:17:30.092 17709-17767/com.bazaarvoice.bv_android_sdk D/Analytics: Successfully posted 1 events

**Comment by caseykulm** [comment]
Thank you for catching this. We plan to get a 3.2.1 release out soon that will include a fix for this.

**Comment by caseykulm** [comment]
Fixed in 3.2.1 release

**Comment by sivaramvanka** [comment]
Thanks for the quick turnaround.
