### ISSUE TITLE
Add Limit On Include Type Crash

### ISSUE THREAD

**Issue by agrosner** [bazaarvoice/bv-android-sdk#17]
The method in `DisplayParams` `addLimitOnIncludedType`
Incorrectly adds the limit to `sortType`:
```
public void addLimitOnIncludedType(IncludeType type, int limitVal) {
		if (limitType == null) {
			limitType = new ArrayList<String>();
		}
		sortType.add("limit_" + type.getTypeString() + "=" + limitVal);
	}
```
when it should add it to the `limitType`:
```
public void addLimitOnIncludedType(IncludeType type, int limitVal) {
		if (limitType == null) {
			limitType = new ArrayList<String>();
		}
		limitType.add("limit_" + type.getTypeString() + "=" + limitVal);
	}
```

**Comment by agrosner** [comment]
This causes a `NullPointerException`

**Comment by caseykulm** [comment]
Thanks for catching this. We will get a hotfix out for this in a 4.0.6 release.

We will also be releasing a revamped version of the conversations portion of this sdk in the upcoming 4.1.0 release.

**Comment by agrosner** [comment]
fantastic. Thank you @caseykulm

**Comment by caseykulm** [comment]
4.1.0 is now available, and although new conversations code has been added, the old code for using conversations has been deprecated, rather than removed. So rather than having a 4.0.6 release we have simply bundled this fix into 4.1.0

**Comment by agrosner** [comment]
Cool are the docs online up to date for usage? Or is there a place I can see usage

**Comment by agrosner** [comment]
Im getting a 404 for the upgrade guide

**Comment by austimkelly** [comment]
@agrosner Hey Andrew - Docs are up. Check out the upgrade guide for old->new usage patterns:

 https://bazaarvoice.github.io/bv-android-sdk/upgrading_conversations.html  

Let us know if you have any other questions.
