### ISSUE TITLE
AnswerOptions.Sort is NOT public.

### ISSUE THREAD

**Issue by agrosner** [bazaarvoice/bv-android-sdk#18]
Version: 4.1.0
I am trying to add an `AnswerOptions.Sort` into a `ProductDisplayRequest.Builder`  and the `addAnswerSort()` method. The `AnswerOptions.Sort` is package private, while the other sorts are public.

**Comment by caseykulm** [comment]
Thanks again for catching more stuff! The fix for this has been released in 4.1.2
