### ISSUE TITLE
Offset In ProductDisplayPageRequest

### ISSUE THREAD

**Issue by agrosner** [bazaarvoice/bv-android-sdk#21]
Previously we could specify an offset via:
```
 DisplayParams params = new DisplayParams();
        params.addFilter(PRODUCT_ID, Equality.EQUAL, itemId);
        params.addSort(SUBMISSION_TIME, false);
        params.addInclude(IncludeType.REVIEWS);
        params.addInclude(IncludeType.COMMENTS);
        params.addStats(IncludeStatsType.REVIEWS);
        params.addLimitOnIncludedType(IncludeType.REVIEWS, MAX_REVIEW_LOAD);
        params.setOffset(offset);
        sendDisplayRequest(params);
```

But in `ProductDisplayRequest.Builder`, the offset is no where to be found.

**Comment by caseykulm** [comment]
It seems like your goal here is to load more reviews? If so our approach to this has changed slightly with the new Conversations API here. The new approach is to first load initial content (up to 20 items of CGC) with the ProductDisplayRequest, and to then load more with the relevant request. So for example if you wanted to load more reviews you would use the ReviewsRequest.Builder(String productId, int limit, int offset) always specifying the offset to start at in the Builder constructor. 

Our docs on https://bazaarvoice.github.io/bv-android-sdk/conversations_display.html outline this in the "Using Conversations Display API" section. The "Product Display Page" tab -> "Loading a Product Display Page" section shows how to get initial content, and the "Reviews" tab -> "Loading more Reviews" section shows how to load more reviews.

If you have any more questions feel free to hit us up at mobilecoreteam@bazaarvoice.com and we can keep any dialog or questions going.

**Comment by agrosner** [comment]
Ok that is fine.
