### ISSUE TITLE
CurationsFeedItem.java

### ISSUE THREAD

**Issue by androidAnDroidAndroid** [bazaarvoice/bv-android-sdk#37]
Hello,
Is there a plan to update the Android Sdk soon?
I noticed two issues:
1. protected Long timestamp: the api does not return a long when the timestamp refers to a item uploaded to bazaarvoice (it has decimal points)
2.protected Long id;: the api seems to return a string

Both of these issues cause a casting error when using the sdk.

**Comment by chris-pound-bazaarvoice** [comment]
Hi,
Thanks for reporting this. We've opened an internal ticket to investigate.

**Comment by chris-pound-bazaarvoice** [comment]
We released 7.0.0 with a fix for this issue. Please see https://github.com/bazaarvoice/bv-android-sdk/commit/b5d7c2feec3a875205c19065f4a5aa8d28eadfda and [Release 7.0.0](https://github.com/bazaarvoice/bv-android-sdk/releases/tag/7.0.0) for details.
