### ISSUE TITLE
Crash in ReviewStatistics.getRatingDistribution

### ISSUE THREAD

**Issue by dannyhm** [bazaarvoice/bv-android-sdk#38]
java.lang.ArrayIndexOutOfBoundsException: length=5; index=-1
        at com.bazaarvoice.bvandroidsdk.ReviewStatistics.getRatingDistribution(ReviewStatistics.java:135)

The rating distribution for this product comes back with a 0 star count, so [container.getRatingValue() -1] does not work in this case.

**Comment by chris-pound-bazaarvoice** [comment]
Thanks for reporting this. We've opened an internal ticket to investigate.

**Comment by chris-pound-bazaarvoice** [comment]
Released fix in [8.2.1](https://github.com/bazaarvoice/bv-android-sdk/tree/8.2.1 )
