### ISSUE TITLE
Wrong BVPixel documentation/initialization

### ISSUE THREAD

**Issue by ema987** [bazaarvoice/bv-android-sdk#40]
Hello,

here to post an issue regarding the documentation/initialization of the BazaarVoice Pixel (BVPixel).

The documentation [here](https://developer.bazaarvoice.com/mobile-sdks/android/modules/bv-pixel) in the section _Installation_ says you should build your own instance of the BVPixel class. Unfortunately doing this will result in a runtime crash when _confirmBvPixelNotCreated_ is called at [line 110 inside BVPixel](https://github.com/bazaarvoice/bv-android-sdk/blob/master/bvanalytics/src/main/java/com/bazaarvoice/bvandroidsdk/BVPixel.java). 

If you see [line 543 inside BVSK class](https://github.com/bazaarvoice/bv-android-sdk/blob/master/bvcommon/src/main/java/com/bazaarvoice/bvandroidsdk/BVSDK.java) the BVPixel is already built there, so when you try to build manually your BVPixel it results in an exception being thrown because the singleton instance already exists.

I think the documentation should be updated removing the whole _Installation_ section and the code can also be updated restricting access to the build method of BVPixel class, so only the BVSDK class can use it.

SDK version: 8.2.2
SDK components: BVPixel

**Comment by chris-pound-bazaarvoice** [comment]
Hi,

The use case for this is to allow BVPixel be it's own independent module. This would allow a client to use BVPixel in their app but not be reliant on the full SDK.  We'll look into updating our documentation to see if  we can make this point clearer.

**Comment by ema987** [comment]
Hi @chris-pound-bazaarvoice,

thank you for your explanation! I wasn't aware of this use case, an updated documentation will surely be helpful to other developers using your SDK.

Thank you!
