### ISSUE TITLE
Google service flagging the play-services sdk (18) being used by Bazaarvoice. 

### ISSUE THREAD

**Issue by varunreddyguda** [bazaarvoice/bv-android-sdk#46]
Hi Bazaarvoice, the current playservices ads sdk mentioned below needs to be upgraded to the latest version. Since current version is being flagged by playstore console which is making our app unable to pass for review. 
Latest version mandated by google : 19.4.0+
![Screenshot 2023-07-21 at 2 31 12 PM](https://github.com/bazaarvoice/bv-android-sdk/assets/119062476/a5686cb2-7f51-4aa9-a476-35a8db636679)

Thanks. 
Varun Reddy Guda
(projectwebappdev@gmail.com).

**Comment by junaidBazaarVoice** [comment]
Hi we have removed play services ads SDK and added. the play-services-ads-identifier instead in version 8.14.0
